### ISSUE TITLE
getting permssion denied when i run bash in kali linux

### ISSUE THREAD

**Issue by personic75** [mishakorzik/AllHackingTools#10]
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)
Install.sh: line 11: pip2: command not found
Install.sh: line 14: cd: AllHackingTools: No such file or directory
python2: can't open file 'src/InstallMenu.py': [Errno 2] No such file or directory

**Comment by mishakorzik** [comment]
Hello! Thanks for the feedback, I will fix the problem. Just write your operating system:

**Comment by mishakorzik** [comment]
I'm sorry, I looked at your problem and want to say that AllHackingTool is not yet supported on Kali Linux
