### ISSUE TITLE
Username and password 

### ISSUE THREAD

**Issue by nilesh-oss** [mishakorzik/AllHackingTools#111]
**Describe the bug**

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mishakorzik** [comment]
simply press Enter.
