### ISSUE TITLE
It removed a lib

### ISSUE THREAD

**Issue by justinruck080** [mishakorzik/AllHackingTools#18]
This tool removed apt-get I don't know how but it just did, how can I reinstall apt ?

**Comment by mishakorzik** [comment]
I apologize but AllHackingTools does not remove apt. Maybe you did something wrong.
What your operating system?

**Comment by mishakorzik** [comment]
if you tell the operating system then I can help you and install apt.

**Comment by justinruck080** [comment]
I'm using termux

**Comment by mishakorzik** [comment]
I don't know but the AllHackingTools system doesn't remove apt. But for termux is pkg it replaces apt.

**Comment by justinruck080** [comment]
If you have Instagram or any social media I'll show you screenshots...
