### ISSUE TITLE
AllHackingTool

### ISSUE THREAD

**Issue by SlavaKali** [mishakorzik/AllHackingTools#19]
Когда должна появиться кнопка  DONE? почему у вас не описанно, что делать на этих этапах? Подскажите пожалуйста
![Screenshot_20211111-001842_Termux](https://user-images.githubusercontent.com/94010284/141197574-5eb340c5-2b97-4b6e-9a47-0cff41556bb0.jpg)
![Screenshot_20211111-001946_Termux](https://user-images.githubusercontent.com/94010284/141197580-68a8ccf0-5c27-47ed-8896-7f7bacb0d851.jpg)

**Comment by mishakorzik** [comment]
На этих этапах все описано в github wiki.  сверху сайта возле баннера есть wikipedia.

И кнопка DONE появится, когда все будет установлено.
