### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by CoolGamer07** [mishakorzik/AllHackingTools#22]
**Describe the bug**
Earlier the tool was working properly but after I updated it, it is showing an error when I run the command.
![Screenshot_2022-01-30-22-59-41-65_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/96921278/151710422-e9a77c6a-79c9-4a94-9d10-f2fd6619727f.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme narzo 30A
 - OS: V11
 - Browser Termux 
Please send the solutions of this.

**Comment by mishakorzik** [comment]
Did you have any problems downloading AllHackingTools?

**Comment by mishakorzik** [comment]
try the command: msdconsole

**Comment by CoolGamer07** [comment]
No problem on downloading

**Comment by CoolGamer07** [comment]
Tried

**Comment by mishakorzik** [comment]
try reinstalling AllHackingTolls

**Comment by mishakorzik** [comment]
report on installation information here: https://github.com/mishakorzik/AllHackingTools/wiki

**Comment by CoolGamer07** [comment]
Thanks, I'll check it out.

**Comment by BLACKHOLE1198** [comment]
How to enter a licence to hack instagram
