### ISSUE TITLE
How to enter a licence to hack instagram

### ISSUE THREAD

**Issue by BLACKHOLE1198** [mishakorzik/AllHackingTools#23]
How to enter a licence to hack instagram

_Originally posted by @BLACKHOLE1198 in https://github.com/mishakorzik/AllHackingTools/issues/22#issuecomment-1056793598_

**Comment by mishakorzik** [comment]
I apologize for answering for so long because I have not seen what this tool is called and in what section?

**Comment by BLACKHOLE1198** [comment]
Then please answer it

**Comment by BLACKHOLE1198** [comment]
How to enter licience ????
