### ISSUE TITLE
It says this

### ISSUE THREAD

**Issue by Yazkun69** [mishakorzik/AllHackingTools#24]
[+]-[Internet Connection]............[ True ]                                                       Reading package lists... Done                     Building dependency tree... Done                  Reading state information... Done                 E: Unable to locate package python                Reading package lists... Done                     Building dependency tree... Done                  Reading state information... Done                 E: Unable to locate package python2               Reading package lists... Done
Building dependency tree... Done                  Reading state information... Done                 E: Unable to locate package pip                   Reading package lists... Done                     Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pip2
Install.sh: line 22: pip: command not found
Install.sh: line 23: pip2: command not found      Install.sh: line 27: python2: command not found

**Comment by mishakorzik** [comment]
It's a not bug.
