### ISSUE TITLE
Add security policy

### ISSUE THREAD

**Issue by murphy60dotcom** [mishakorzik/AllHackingTools#31]
The security policy doesn't say how to report vulnerability, it is the template security policy so it doesn't have email to send to or where to report.

**Comment by mishakorzik** [comment]
Okay, trank you.

**Comment by murphy60dotcom** [comment]
It still hasn't changed, I don't believe this issue is resolved.

https://github.com/mishakorzik/AllHackingTools/blob/7d366e22cfb29639e7cdbe524ff92b0c0a153304/SECURITY.md?plain=1#L15-L21

Here's an example of a helpful security policy: [SECURITY.md](https://github.com/seL4/seL4/blob/master/SECURITY.md)
