### ISSUE TITLE
Bug menu

### ISSUE THREAD

**Issue by HotLava30** [mishakorzik/AllHackingTools#33]
**Describe the bug**
I found a bug that when you write 01 (information gathering) it doesn't show the menu and only shows a code

**Screenshots**
![Screenshot_20220605-122854](https://user-images.githubusercontent.com/72771726/172036891-497551db-89c3-41af-9ca3-cd6530e3eed7.png)

**Smartphone (please complete the following information):**
 - Device: Asus ZenFone max pro m1
 - OS: Android 9
 - Browser Termux
 - Version 0.118.0

**Comment by mishakorzik** [comment]
Reinstall
