### ISSUE TITLE
What is get.py?

### ISSUE THREAD

**Issue by murphy60dotcom** [mishakorzik/AllHackingTools#34]
What does [`Files/get.py`](https://github.com/mishakorzik/AllHackingTools/blob/0f32af2a2c2e5060228e0fbf294e26ca73025b0f/Files/get.py) do?
How do you run it?
What is it getting?

**Comment by murphy60dotcom** [comment]
When I try to run it, like it's run here:

https://github.com/mishakorzik/AllHackingTools/blob/7d366e22cfb29639e7cdbe524ff92b0c0a153304/MainMenu.py#L16

python exits with a syntax error.

```console
$ python3 Files/get.py
SyntaxError: Non-UTF-8 code starting with '\xa0' in file .../Files/get.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

How is it supposed to be run?
It's not regular python source code, it looks byte compiled or something.

**Comment by murphy60dotcom** [comment]
Before I had an outdated python but now its to 3.10 and it decompiles.

This is an ip grabber? The email and password are embedded for the `examples0jk@yahoo.com` account which is not secure.
It sends an email with the json from api.ipdata.co (informaton about user's ip address) to `miguardzecurity@gmail.com`.

```python3
# Source Generated with Decompyle++
# File: get.py (Python 3.10)

import smtplib
import requests
import random
user = 'examples0jk@yahoo.com'
pwd = 'stcbaqzrlpmdnwnl'
ipdata_list = [
    'https://api.ipdata.co/?api-key=6818a70bf0dcdbf1dd6bf89e62299740a49725ac65ff8e4056e3b343',
    'https://api.ipdata.co/?api-key=7d9bf69a54c63b6f9274c6074b2f50aee46208d10a33533452add840',
    'https://api.ipdata.co/?api-key=6453632fcabd2a4c2de4bb45ab35254594fd719e61d58bacde4429f0',
    'https://api.ipdata.co/?api-key=6aed0320c458287bdc453ce543c6edc565fd098eda4a79f7e41b3b61']
ipdata = random.choice(ipdata_list)
body = requests.get(ipdata).text
message = 'Subject: Log\n\n' + body
server = smtplib.SMTP('smtp.mail.yahoo.com', 587)
server.starttls()
server.login(user, pwd)
server.sendmail(user, 'miguardzecurity@gmail.com', message)
```

**Comment by murphy60dotcom** [comment]
It doesn't say anywhere in [ReadMe](README.md) that it sends user IP Address to the email. That is not okay to do, to spy on users without consent.

**Comment by Zerocool1871** [comment]
This whole thing seems dodgy AF, why some broke ass dude trying to hack others on this platform is just pathetic....

**Comment by mishakorzik** [comment]
This is a log to prevent problems if there are any with this tool.

**Comment by mishakorzik** [comment]
and it is not made for hacking.

**Comment by mishakorzik** [comment]
> It doesn't say anywhere in [ReadMe](README.md) that it sends user IP Address to the email. That is not okay to do, to spy on users without consent.

And so that everything was fine, I wrote it in README.md

**Comment by Zerocool1871** [comment]
That's not much of a explanation,  also the Readme doesn't have to say it. It can just be put there thinking no 1 would find it. So please do elaborate with regards to what Murphy has come across? Cause I doubt he sucked this out is thumb.

**Comment by murphy60dotcom** [comment]
What is idle about it? The file runs every time in MainMenu.py.
https://github.com/mishakorzik/AllHackingTools/blob/8eb63a4f8a2652b26834228643aba1fdb9d68857/MainMenu.py#L16

**Comment by murphy60dotcom** [comment]
How are you go to prevent problems by only having IP address and location?

**Comment by murphy60dotcom** [comment]
For anyone who is wanting to see how to get python code from the binary compiled file, I used https://github.com/zrax/pycdc.

**Comment by mishakorzik** [comment]
get.py is discussed at the beginning of README.md
