### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by murtaza9292** [mishakorzik/AllHackingTools#40]
Sir,
I am facing an issue. It shows an error of get.py no such file or directory. 
![Screenshot_20220818-122235](https://user-images.githubusercontent.com/32122168/185334715-4b400e79-5d7d-4cf2-9d6f-345a764a39cc.png)
Kindly see the attached screenshot. Thank you

**Comment by kilammalik** [comment]
Same error with me, everything from All hack tools folder is depleted

**Comment by mishakorzik** [comment]
Okay

**Comment by mishakorzik** [comment]
cd AllHackingTools
nano MainMenu.py
goto 16 line
delete 16 line

**Comment by doceducates** [comment]
Thank you for your response dear really appreciated
