### ISSUE TITLE
[-]-[Internet Connection].........[ False ]

### ISSUE THREAD

**Issue by Ttrmaniac** [mishakorzik/AllHackingTools#41]
[-]-[Internet Connection].........[ False ]
IS what it says when i try running it brr

**Comment by mishakorzik** [comment]
Your operating system

**Comment by Ttrmaniac** [comment]
its Windows Im using gitpod.io terminal

**Comment by Ttrmaniac** [comment]
And I was trying to tweak this project

**Comment by mishakorzik** [comment]
AllHackingTools not supported on windows

**Comment by Ttrmaniac** [comment]
oh
