### ISSUE TITLE
did you leave this in on purpose?

### ISSUE THREAD

**Issue by webmaster-exit-1** [mishakorzik/AllHackingTools#42]
# Developer   : misha korzhik
# config code : 14nY2wpMs82oU49ThI7

# user : Administrator
# pass : Adm1_control

I think you left your user and password in the tool

**Comment by Kiiryamark** [comment]
********

**Comment by mishakorzik** [comment]
This configuration is not work, I once wanted to make servers, but then I changed my mind.
