### ISSUE TITLE
the error I have is in termux since when I put the git clone it does not clone I do not know if they have already deleted the repository please tell me what to do

### ISSUE THREAD

**Issue by Gato201** [mishakorzik/AllHackingTools#43]
#**Describe the bug**

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mishakorzik** [comment]
Its not problem AllHackingTools.
