### ISSUE TITLE
File "Files/IpMenu.py", line 85
    elif(op==17):
       ^
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Nasika5** [mishakorzik/AllHackingTools#45]
I'm getting this error.

![Screenshot_2022-11-30-09-11-35-882_com.termux.jpg](https://user-images.githubusercontent.com/108931896/204730937-81634ca2-22be-4c12-bdf5-260dd4ee7277.jpg)

**Comment by mishakorzik** [comment]
Tranks for report bug

**Comment by mishakorzik** [comment]
I fixed error, please reinstall AllHackingTools.
