### ISSUE TITLE
File "Files/PhishingMenu.py", line 26

elif (op==1): SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Nasika5** [mishakorzik/AllHackingTools#46]
Now, I'm getting this error
![Screenshot_2022-12-03-18-44-40-562_com.termux.jpg](https://user-images.githubusercontent.com/108931896/205477949-49464e90-23ae-455d-9933-7f4eaa375231.jpg)

**Comment by mishakorzik** [comment]
Fixed, reinstall AllHackingTools or: nano /data/data/com.termux/files/homeAllHackingTools/Files/PhishingMenu.py 
clear 26 line and write this: if(op==1):
