### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SmindHOTX** [mishakorzik/AllHackingTools#47]
![Screenshot_2023-01-07-17-46-54-68_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/121820870/211146465-c334ce37-f5a0-4e3a-842d-668341f5fe88.jpg)

Help !

**Comment by Rehan111888** [comment]
> ![Screenshot_2023-01-07-17-46-54-68_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/121820870/211146465-c334ce37-f5a0-4e3a-842d-668341f5fe88.jpg)
> 
> Help !

Type Msdc

**Comment by Phoenixonf1re** [comment]
Hey Mishakorzik/Allhackingtools how are you?
I’m really new to all this and would love some coaching or mentoring
Dan

**Comment by mishakorzik** [comment]
if you want to configure ngrok on termux, write the command "pkg install proot-distro" and "proot-distro install ubuntu" when you have everything installed, and to start ngrok write the command "proot-distro login ubuntu" and start ngrok there already, because ngrok  no longer works on termux

**Comment by mishakorzik** [comment]
if you want to run AllHackingTools, write the command: msdc or msdconsole
