### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by lilithmodz** [mishakorzik/AllHackingTools#48]
![Screenshot_2023-01-19-09-09-41-939_com.termux.jpg](https://user-images.githubusercontent.com/122872014/213389154-450af71b-9735-4015-91f2-c07a055286be.jpg) that happens idk what ti do, After that i run bash Install.sh and It shows ![Screenshot_2023-01-19-09-13-05-645_com.termux.jpg](https://user-images.githubusercontent.com/122872014/213389296-bcf028b8-463f-4905-ba78-8308b915d71f.jpg) what should i do?
at this point idk what to run..

**Comment by Rehan111888** [comment]
> ![Screenshot_2023-01-19-09-09-41-939_com.termux.jpg](https://user-images.githubusercontent.com/122872014/213389154-450af71b-9735-4015-91f2-c07a055286be.jpg) that happens idk what ti do, After that i run bash Install.sh and It shows ![Screenshot_2023-01-19-09-13-05-645_com.termux.jpg](https://user-images.githubusercontent.com/122872014/213389296-bcf028b8-463f-4905-ba78-8308b915d71f.jpg) what should i do?
> at this point idk what to run..

Choose 1.Default
