### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Seraphinfire** [mishakorzik/AllHackingTools#49]
![_20230123_210243](https://user-images.githubusercontent.com/46533277/214138834-d8cff7f9-a0cc-4d69-9f22-166c8b0d75e4.JPG)

This is what happens when I type 01 in the menu

**Comment by Seraphinfire** [comment]
I try to do bash fix.sh but no results 
Thanks by advance for your help

**Comment by mishakorzik** [comment]
this bug has been fixed a long time ago, update AllHackingTools to the latest version

**Comment by Seraphinfire** [comment]
Thanks for your response
Have à good day
