### ISSUE TITLE
Missing files and packages

### ISSUE THREAD

**Issue by onxno** [mishakorzik/AllHackingTools#50]
**Describe the bug**
Missing files and packages - unable to fix it

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**
I expected the program to work ;)
But some options have missing files and modules

 - Device: [Samsung fold4]
 - OS: [Newest android, but AHT working on termux]

**Additional context**
![Screenshot_20230129_221825_Termux](https://user-images.githubusercontent.com/95235388/215356499-3fbf6cce-9da2-4d11-bedd-1c622e83ab37.jpg)
![Screenshot_20230129_221610_Termux](https://user-images.githubusercontent.com/95235388/215356501-762d886c-3e8a-4f1f-869e-cfbb6e0066b2.jpg)
![Screenshot_20230129_221917_Termux](https://user-images.githubusercontent.com/95235388/215356502-c62c4ceb-bfdb-499d-b070-91f7d9c85119.jpg)
![Screenshot_20230129_222029_Termux](https://user-images.githubusercontent.com/95235388/215356504-c24ac7da-6855-476f-81ac-632304a4bf0a.jpg)
![Screenshot_20230129_221537_Termux](https://user-images.githubusercontent.com/95235388/215356505-9405dc78-26b3-4afb-a508-a9b750c9fad6.jpg)

**Comment by mishakorzik** [comment]
You have incorrectly installed AllHackingTools, reinstall and write "pip install rich" & "pip install furure"

**Comment by onxno** [comment]
Was installed using instructions provided, still not working properly, lots of tools bugging

**Comment by mishakorzik** [comment]
You android and termux version?

**Comment by onxno** [comment]
Ok, so i had termux from kali store, if you use one from f droid it works.

**Comment by mishakorzik** [comment]
Okay
