### ISSUE TITLE
"Maybe you don't have internet" how to fix it

### ISSUE THREAD

**Issue by user-name00** [mishakorzik/AllHackingTools#51]
**Describe the bug**
it was installed successfully but when i start it by msdc it says MainMenu.py not found and the next it shows the msg saying maybe you don't have internet 

**To Reproduce**
idk

**Screenshot**
![Screenshot_20230201-220822_Termux](https://user-images.githubusercontent.com/124184037/216106888-58628b80-da43-4521-8ffc-af5975f1407b.png)

**Smartphone (please complete the following information):**
 - Device: realme 2 pro (rooted)
 - OS: Aosp Extended A12
 - Terminal: Termux

**Comment by mishakorzik** [comment]
maybe you have some problems with the Internet, try to start again

**Comment by mishakorzik** [comment]
it happened because you had bad internet if you have good internet then you have problems with github host
