### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Yasisine9** [mishakorzik/AllHackingTools#52]
Hello, when I use a tool like phising and others it tell me direct link but there are no link...
Thank you for responding me !

**Comment by mishakorzik** [comment]
which phishing tool did you use?

**Comment by mishakorzik** [comment]
this is due to ngrok issue try to start ngrok manually

**Comment by Tartiflette1276** [comment]
How ??

**Comment by mishakorzik** [comment]
you need to install ngrok or try via serveo it's an easier option
