### ISSUE TITLE
error import requests module, module not found

### ISSUE THREAD

**Issue by termux-sam** [mishakorzik/AllHackingTools#53]
When I started to use Allhackingtools for the first time today, it seemed to work to some degree - I was able to make it into the main menu, but now i'm getting this error:

"File "MainMenu.py", line 1, in <module>
    import requests
ImportError: No module named requests"

when I type msdc

and when i try to import the requests module, it says it is already imported

any ideas?

**Comment by mishakorzik** [comment]
Its python pip module bug try: pip install requests
