### ISSUE TITLE
Problème "Main.py ligne 6"

### ISSUE THREAD

**Issue by Seraphinfire** [mishakorzik/AllHackingTools#56]
Hi, 

I have a problem, 
I try "pip install requests"
try "apt update and upgrade"
Checked update on my phone, termux etc 
I don't find the problem

Can you help me please ?
Thank you by advance
![1678608937295__20230306_151506](https://user-images.githubusercontent.com/46533277/224532669-59704ae3-cf75-441c-a719-418d414701b0.JPG)

**Comment by mishakorzik** [comment]
Its python bug try: pip install requests

**Comment by Seraphinfire** [comment]
Thanks for you answer
But..But.. 
I wrote to you that I already did... "Pip install requests"
