### ISSUE TITLE
How can I disable all banners?

### ISSUE THREAD

**Issue by vzlomano303** [mishakorzik/AllHackingTools#60]
How do I disable all banners ?
![Screenshot_20230602_223405_Termux](https://github.com/mishakorzik/AllHackingTools/assets/54184395/7e99de97-9479-4054-8525-248239317a05)
Thanks in advance

**Comment by mishakorzik** [comment]
copy and write this command to terminal:
rm -rf /data/data/com.termux/files/usr/etc/zshrc
