### ISSUE TITLE
Hu

### ISSUE THREAD

**Issue by Frydzyslaw** [mishakorzik/AllHackingTools#65]
**Describe the bug**

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mishakorzik** [comment]
Email misakorzik528@gmail.com Not working, if you have problems, you can open a new Issue.
