### ISSUE TITLE
the internet error termux

### ISSUE THREAD

**Issue by ilyas999** [mishakorzik/AllHackingTools#68]
the problem is when you bash install.sh they told me conection error is there is there is any solution?

![Screenshot_2023-07-18-05-47-59-250_com termux](https://github.com/mishakorzik/AllHackingTools/assets/72867322/e8bf5b78-9c12-411e-aee8-d6ed93f47a9b)

**Comment by mishakorzik** [comment]
I fixed error, reinstall AllHackingTools.
