### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by prajwalsharma124** [mishakorzik/AllHackingTools#69]
**Describe the bug**

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mishakorzik** [comment]
What your operating system?

**Comment by prajwalsharma124** [comment]
Kali Linux

**Comment by mishakorzik** [comment]
AllHackingTools is not supported on Kali Linux. You need to install on termux.
