### ISSUE TITLE
poor

### ISSUE THREAD

**Issue by tmmm937** [mishakorzik/AllHackingTools#70]
**Describe the bug**

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zain010101** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. See error
> 2. Go to 'misakorzik528@gmail.com'
> 3. Send me bug 
> 4. Screanshot and text
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. iOS]
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
>  - Device: [e.g. iPhone6]
>  - OS: [e.g. iOS8.1]
>  - Browser [e.g. stock browser, safari]
>  - Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.
> 

Means?

**Comment by Zain010101** [comment]
> poor

Means poor?
