### ISSUE TITLE
Pip2 problem

### ISSUE THREAD

**Issue by Jlsorr** [mishakorzik/AllHackingTools#73]
I tried somehow but nothing worked

`E: Impossible de trouver le paquet pip2
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.31.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv          
Install.sh: ligne 19: pip2 : commande introuvable                            
Install.sh: ligne 22 : cd: AllHackingTools: Aucun fichier ou dossier de ce type
python2: can't open file 'src/InstallMenu.py': [Errno 2] No such file or directory
`

**Comment by mishakorzik** [comment]
You installed termux from fdroid?
