### ISSUE TITLE
Some of the tools isn't working 

### ISSUE THREAD

**Issue by Miroslaw96** [mishakorzik/AllHackingTools#75]
![Screenshot_2023-09-15-09-05-13-958_com termux](https://github.com/mishakorzik/AllHackingTools/assets/145011252/00207da8-e1f2-4292-85d7-3b21c29c94a5)
![Screenshot_2023-09-15-09-06-21-582_com termux](https://github.com/mishakorzik/AllHackingTools/assets/145011252/2d9821b7-ce3a-4528-8cd9-b5f809010125)
![Screenshot_2023-09-15-09-21-59-959_com termux](https://github.com/mishakorzik/AllHackingTools/assets/145011252/ffe707b3-b904-41a2-9d16-5061b2f14d99)

**Comment by Miroslaw96** [comment]
![Screenshot_2023-09-15-09-43-09-706_com termux](https://github.com/mishakorzik/AllHackingTools/assets/145011252/fb79f798-8f1d-4342-82bf-b324376758c6)

**Comment by Miroslaw96** [comment]
![Screenshot_2023-09-15-10-00-59-862_com termux](https://github.com/mishakorzik/AllHackingTools/assets/145011252/6973815b-ed91-4137-b470-77dc2be0b76f)

**Comment by Jooh1** [comment]
The file was not downloaded
When running the configuration
And the code seem to have
Available
The code was enc encrypted with the programer password
