### ISSUE TITLE
Cd no sush file or directory

### ISSUE THREAD

**Issue by D3amon** [mishakorzik/AllHackingTools#79]
When attempting 
cd AllHackingtools

It responds with
No such file or directory
/`
![Screenshot_20231029-165352_Termux](https://github.com/mishakorzik/AllHackingTools/assets/149318935/7fb30ddc-ec85-4b2e-a183-c71ed8f739e7)
`

**Comment by destiny788** [comment]
Hi

**Comment by mishakorzik** [comment]
If not such file or directory you not installed AllHackingTools
