### ISSUE TITLE
Hey how can i contact you 

### ISSUE THREAD

**Issue by naresh556677** [mishakorzik/AllHackingTools#81]
~ $ cd
~ $ ls
23.11.08           adbfiles      sqlmap
AdminHack          anonymous     termux_webscan
GhostTrack         insfollow     torshammer
InstallTools.sh.1  owscan        weeman
Rxce.hack          secretfinder  zphisher
~ $ cd AdminHack
~/AdminHack $ ls
AdminHack.sh  index.html    setup.sh      wordlist1.txt
LICENSE       index.html.1  src           wordlist2.txt
README.md     jiowin.co.in  wordlist.txt
~/AdminHack $ cd README.md
bash: cd: README.md: Not a directory
~/AdminHack $ python2 README.md
  File "README.md", line 1
    <img width="99.9%" src="https://raw.githubusercontent.com/mishakorzik/mishakorzik.menu.io/master/img/AdminHackImg/IMG-adc29ed25806177260186a4fbdbe70c9-V.jpg"/>
    ^

Please tell me what I do

**Comment by mishakorzik** [comment]
To start AdminHack copy command: cd AdminHack && bash AdminHack.sh
