### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ProoSpyy** [mishakorzik/AllHackingTools#83]
When I start the program, I get an error like this "Options: Traceback (most recent call last):
  File "MainMenu.py", line 31, in <module>
    op=int(raw_input("Options: "))
ValueError: invalid literal for int() with base 10: ''
![Uploading Screenshot_20231126_011546_com.termux.jpg…]()

**Comment by mishakorzik** [comment]
Your start program with «msdc» command?
