### ISSUE TITLE
Help! Cannot cd to the directory 

### ISSUE THREAD

**Issue by gary8619** [mishakorzik/AllHackingTools#84]
Hi,

Please advise me the following error. i have try to give permission and using root to access but nothing works. 

Options: 14
[INFO]Starting tool menu. Please wait a moment!
[WARN]A don't close termux app! And exit termux!
sh: 1: cd: can't cd to AllHackingTools

**Comment by mishakorzik** [comment]
Your installed AllHackingTools in /data/data/com.termux/files/home?
