### ISSUE TITLE
AIDE SVP

### ISSUE THREAD

**Issue by lysandrevb** [mishakorzik/AllHackingTools#87]
je suis français je voudrais savoir comment faire pour utiliser et installer ça please

**Comment by lysandrevb** [comment]
C:\Users\lysan\OneDrive\Bureau\Tools\AllHackingTools-main>python3 MainMenu.py
Traceback (most recent call last):
  File "C:\Users\lysan\OneDrive\Bureau\Tools\AllHackingTools-main\MainMenu.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by mishakorzik** [comment]
AllHackingTools doesn't support windows.
