### ISSUE TITLE
Install.sh: line 22: cd: AllHackingTools: No such file or directory python2: can't open file 'src/InstallMenu.py': [Errno 2] No such file or directory ~/SocialBox-Termux/AllHackingTools $ cd AllHackingTools bash: cd: AllHackingTools: No such file or directory

### ISSUE THREAD

**Issue by Rgb8746** [mishakorzik/AllHackingTools#88]
I get this error or something evrytime and it Shops. There
![Screenshot_20240215_204841_Termux](https://github.com/mishakorzik/AllHackingTools/assets/137738253/ffcf4b03-fdef-4b88-9e01-ca099789252b)

**Comment by mishakorzik** [comment]
You need to install AllHackingTools in $HOME directory not in 'SocialBox-Termux' directory

**Comment by LNLenost** [comment]
> You need to install AllHackingTools in $HOME directory not in 'SocialBox-Termux' directory

How to do this??
