### ISSUE TITLE
How do I support this pen testing tool? Or add a tool to it? This is better than fsociety

### ISSUE THREAD

**Issue by Mrhssjsh** [mishakorzik/AllHackingTools#89]
**Is your feature request related to a problem? Please describe.**
A clear and coen [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by mishakorzik** [comment]
if you want me to add some tool, you can send me a link to it and I will check it.
