### ISSUE TITLE
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8) error: 7751 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF

### ISSUE THREAD

**Issue by Revenger112** [mishakorzik/AllHackingTools#98]
**Describe the bug**

**To Reproduce**
1. See error
2. Go to 'misakorzik528@gmail.com'
3. Send me bug 
4. Screanshot and text

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mishakorzik** [comment]
Can you send a screenshot of error? Please
